services:
  my-react-app:
    build:
      context: .
    working_dir: /app
    ports:
      - "4500:4500"
    volumes:
      - ./my-react-app:/app
      - /app/node_modules  # ホストの node_modules を無視
    command: npm run dev
